// This module includes the Rust code generated by tonic_build from the .proto file.
// The name `mos_robot_v1` corresponds to the package name `mos.robot.v1` in the .proto file.
pub mod mos_robot_v1 {
    tonic::include_proto!("mos.robot.v1");
}
