// This file is @generated by prost-build.
/// ================== Robot Control 模块 ==================
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetJointAnglesRequest {
    /// 目标关节角度列表
    #[prost(double, repeated, tag = "1")]
    pub angles: ::prost::alloc::vec::Vec<f64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetJointAnglesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJointAnglesResponse {
    /// 当前关节角度列表
    #[prost(double, repeated, tag = "1")]
    pub angles: ::prost::alloc::vec::Vec<f64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommandResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// ================== Task 模块 ==================
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TaskRequest {
    /// 任务 ID，客户端可选，由服务器分配
    #[prost(int64, optional, tag = "1")]
    pub id: ::core::option::Option<i64>,
    /// 优先级
    #[prost(uint32, tag = "2")]
    pub priority: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TaskResponse {
    /// 返回任务 ID（通常与请求一致）
    #[prost(uint64, tag = "1")]
    pub id: u64,
}
/// ================== Telemetry 模块 ==================
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TelemetryRequest {
    /// 传感器 ID，例如 "camera_1"、"lidar_2"
    #[prost(string, tag = "1")]
    pub sensor_id: ::prost::alloc::string::String,
    /// 原始遥测数据（可选）
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// 时间戳（Unix 秒）
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}
/// ✅ 新的 TelemetryData，用于流式下行
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryData {
    /// 数据来源，例如 "mock_sensor"
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// 传感器数值
    #[prost(double, tag = "2")]
    pub value: f64,
    /// 时间戳（秒）
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
}
/// ================== 通用响应（可选扩展） ==================
///
/// 如果未来某些 RPC 需要返回状态/错误信息，可以继续使用这个结构。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TelemetryResponse {
    /// 响应 ID
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 是否成功
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// 响应消息
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod mos_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// 主服务：统一的机器人任务与遥测流接口
    #[derive(Debug, Clone)]
    pub struct MosClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MosClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MosClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MosClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MosClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 一次性任务调度（请求 -> 响应）
        pub async fn schedule_task(
            &mut self,
            request: impl tonic::IntoRequest<super::TaskRequest>,
        ) -> std::result::Result<tonic::Response<super::TaskResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/mos.Mos/ScheduleTask");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("mos.Mos", "ScheduleTask"));
            self.inner.unary(req, path, codec).await
        }
        /// 双向流式遥测通信（客户端可以发送 TelemetryRequest，服务端推送 TelemetryData）
        pub async fn stream_telemetry(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::TelemetryRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::TelemetryData>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/mos.Mos/StreamTelemetry");
            let mut req = request.into_streaming_request();
            req.extensions_mut().insert(GrpcMethod::new("mos.Mos", "StreamTelemetry"));
            self.inner.streaming(req, path, codec).await
        }
        /// 设置机器人关节角度
        pub async fn set_joint_angles(
            &mut self,
            request: impl tonic::IntoRequest<super::SetJointAnglesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CommandResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/mos.Mos/SetJointAngles");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("mos.Mos", "SetJointAngles"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取机器人当前关节角度
        pub async fn get_joint_angles(
            &mut self,
            request: impl tonic::IntoRequest<super::GetJointAnglesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetJointAnglesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/mos.Mos/GetJointAngles");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("mos.Mos", "GetJointAngles"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod mos_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MosServer.
    #[async_trait]
    pub trait Mos: std::marker::Send + std::marker::Sync + 'static {
        /// 一次性任务调度（请求 -> 响应）
        async fn schedule_task(
            &self,
            request: tonic::Request<super::TaskRequest>,
        ) -> std::result::Result<tonic::Response<super::TaskResponse>, tonic::Status>;
        /// Server streaming response type for the StreamTelemetry method.
        type StreamTelemetryStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::TelemetryData, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// 双向流式遥测通信（客户端可以发送 TelemetryRequest，服务端推送 TelemetryData）
        async fn stream_telemetry(
            &self,
            request: tonic::Request<tonic::Streaming<super::TelemetryRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamTelemetryStream>,
            tonic::Status,
        >;
        /// 设置机器人关节角度
        async fn set_joint_angles(
            &self,
            request: tonic::Request<super::SetJointAnglesRequest>,
        ) -> std::result::Result<tonic::Response<super::CommandResponse>, tonic::Status>;
        /// 获取机器人当前关节角度
        async fn get_joint_angles(
            &self,
            request: tonic::Request<super::GetJointAnglesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetJointAnglesResponse>,
            tonic::Status,
        >;
    }
    /// 主服务：统一的机器人任务与遥测流接口
    #[derive(Debug)]
    pub struct MosServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MosServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MosServer<T>
    where
        T: Mos,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/mos.Mos/ScheduleTask" => {
                    #[allow(non_camel_case_types)]
                    struct ScheduleTaskSvc<T: Mos>(pub Arc<T>);
                    impl<T: Mos> tonic::server::UnaryService<super::TaskRequest>
                    for ScheduleTaskSvc<T> {
                        type Response = super::TaskResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TaskRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Mos>::schedule_task(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ScheduleTaskSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/mos.Mos/StreamTelemetry" => {
                    #[allow(non_camel_case_types)]
                    struct StreamTelemetrySvc<T: Mos>(pub Arc<T>);
                    impl<T: Mos> tonic::server::StreamingService<super::TelemetryRequest>
                    for StreamTelemetrySvc<T> {
                        type Response = super::TelemetryData;
                        type ResponseStream = T::StreamTelemetryStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::TelemetryRequest>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Mos>::stream_telemetry(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamTelemetrySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/mos.Mos/SetJointAngles" => {
                    #[allow(non_camel_case_types)]
                    struct SetJointAnglesSvc<T: Mos>(pub Arc<T>);
                    impl<
                        T: Mos,
                    > tonic::server::UnaryService<super::SetJointAnglesRequest>
                    for SetJointAnglesSvc<T> {
                        type Response = super::CommandResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetJointAnglesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Mos>::set_joint_angles(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetJointAnglesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/mos.Mos/GetJointAngles" => {
                    #[allow(non_camel_case_types)]
                    struct GetJointAnglesSvc<T: Mos>(pub Arc<T>);
                    impl<
                        T: Mos,
                    > tonic::server::UnaryService<super::GetJointAnglesRequest>
                    for GetJointAnglesSvc<T> {
                        type Response = super::GetJointAnglesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetJointAnglesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Mos>::get_joint_angles(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetJointAnglesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MosServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "mos.Mos";
    impl<T> tonic::server::NamedService for MosServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
